apiVersion: v1
kind: Pod
metadata:
   name: mongo-pod
   labels:
      name: mongo-pod
      app: photegrity
spec:
  containers:
  - name: mongodb
    image: mongo
    ports: 
    - containerPort: 27017
    volumeMounts:
    - name: mongodb-persistence
      mountPath: /data/db
  volumes:
    - name: mongodb-persistence
      hostPath:
        path: /c/MongoData/
        type: Directory

