apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
spec:
  capacity:
    storage: 2000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /c/MongoData/
    
