apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-service
    app: photegrity
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    name: mongo-pod
    app: photegrity
    