apiVersion: v1
kind: Service
metadata:
  name: photo-service
  labels:
    name: photo-service
    app: photegrity
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
  selector:
    name: photo
    